### ISSUE TITLE
Datos perfil, configuración perfil y menú

### ISSUE THREAD

**Issue by Leticia-23** [UNIZAR-30226-2021-07/web#101]
Todos los datos de user_data que están repartidos entre estas dos pantallas, que se carguen al iniciar la app. Los users que no han podido comprar tienen unos datos por defecto, pero será misma funcionalidad que cuando haya que cambiar a los de su compra.

- [x]  Usuario (pantalla editar perfil)
- [ ]  Imagen perfil (pantalla menú)
- [x]  Color tablero (pantalla editar perfil)
- [x]  Huellitas que tiene el usuario (pantalla menú)

**Comment by jmarindiez** [comment]
@Leticia-23 lo de imagen de perfil en la pantalla de menú a que te refieres exactamente?

Si es esto, salvo que queramos cambiar la decisión, está bien. Es un icono, no la imagen que el usuario tiene de perfil.
![imagen](https://user-images.githubusercontent.com/45235914/114691380-e5ca9680-9d17-11eb-9db5-5b67aa7db4e1.png)


Puedes cerrar el issue si ya esta todo.
