### ISSUE TITLE
No puedo cambiar el nombre de usuario

### ISSUE THREAD

**Issue by xzebra** [UNIZAR-30226-2021-07/web#120]
Estaba probando en movil y no me deja editar el nombre de usuario. No puedo acceder a la consola por si hay un error. Luego intento replicarlo.

**Comment by jmarindiez** [comment]
El problema esta en que no se hace `handleSubmit`. Parece ser que los eventos dentro de un `Link` se pierden por algun motivo que desconozco.

**Comment by xzebra** [comment]
creo que el problema está en que el botón de submit está fuera del form, no?

**Comment by jmarindiez** [comment]
No, esta dentro. 
![image](https://user-images.githubusercontent.com/45235914/115141167-35240600-a03b-11eb-9f6c-e40eee223b6a.png)


Al principio tambien he pensado eso, y lo he puesto dentro de un:
```javascript
<Form.Group>
    <Form.Row>
      ...
    </Form.Row>
</Form.Group>
```

pero nada. Sigue sin hacerse el `handle`

**Comment by jmarindiez** [comment]
He cambiado la forma de hacer el link y ahora va. De todas formas no estoy 100% seguro de que sea eso, pero bueno.

**Comment by xzebra** [comment]
ah vale si ya lo he visto, luego lo reviso pues
