### ISSUE TITLE
Pantalla de ayuda

### ISSUE THREAD

**Issue by Leticia-23** [UNIZAR-30226-2021-07/web#139]
Se trata de la pantalla de reglas.
Realizar cuando se tenga tiempo en cualquiera de los sprints. Tiene prioridad todo lo demás.

**Comment by FCanfran** [comment]
- [x] Poner popup scrolleable con `Help` -> si se manda el `remainder_time` desde back-end entonces no haria falta poner `Help` desde match en el popup.
