### ISSUE TITLE
Componente temporizador

### ISSUE THREAD

**Issue by Leticia-23** [UNIZAR-30226-2021-07/web#149]

**Comment by FCanfran** [comment]
@UNIZAR-30226-2021-07/backend esto se refiere a la escucha del evento de turno (el del propio jugador o de los rivales) que llega por parte del servidor?

**Comment by marioortizmanero** [comment]
Los del backend tenemos un temporizador pero solo sirve para pasar el turno automáticamente. No enviamos su valor en ningún momento, así que los del frontend necesitáis llevar otro al mismo tiempo cuando se pase un turno nuevo para podérselo enseñar al usuario.
