### ISSUE TITLE
Mejoras cronometro

### ISSUE THREAD

**Issue by jmarindiez** [UNIZAR-30226-2021-07/web#195]
* Parar  cuando la partida esta pausada.
* Ocultar cuando no es turno del jugador

@UNIZAR-30226-2021-07/app no se si lo habeis tenido en cuenta

**Comment by Tomenos18** [comment]
Sí, cuando se pausa y el del turno se le para el crono y cuando no es su turno, se pone el crono en gris para que parezca desactivado

**Comment by jmarindiez** [comment]
¿Pero aunque este desactivado sigue corriendo y mostrando el tiempo del rival?

**Comment by Tomenos18** [comment]
Desactivado significa que está parado con fondo gris

**Comment by Tomenos18** [comment]
Y si es tu turno, cuando llega una pausa, se para el contador y cuando se vuelve de la pausa, el contador continua

**Comment by jmarindiez** [comment]
Vale, pero yo creo que es mejor ocultarlo. Para tener algo desactivado que no hace nada mas que molestar mejor se quita.

En app si os es mas comodo dejadlo como lo teneis y ya

**Comment by Tomenos18** [comment]
Lo dejamos, queda flamo que se quede gris, al menos para la app queda mejor si se deja que si se quita
