### ISSUE TITLE
Borrar estado de cartas que guardan estado entre turnos

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/web#214]
> las cartas que guardan el estado de quien se ha seleccionado previamente, estaria bien que se borrara el estado en cada turno

> y si ya has seleccionado a 2 que tambien se borre

> lo digo porque si te equivocas eligiendo 2 jugadores, luego ya no puedes elegir a otros 2

**Comment by marioortizmanero** [comment]
Notar que tiene que pasar al *inicio* del turno y no al final

**Comment by FCanfran** [comment]
Casos importantes a corregir: estado se guarda aunque no sea el turno, y limpiar al final de turno por si al final no se utiliza -> limpieza al prinicipio de turno del estado
