### ISSUE TITLE
Popup no es realmente un popup

### ISSUE THREAD

**Issue by xzebra** [UNIZAR-30226-2021-07/web#35]
El popup no se muestra realmente como un popup, se muestra como un componente más.
![image](https://user-images.githubusercontent.com/20362769/111887157-6c1ee180-89d3-11eb-82db-8b60fbde7a0b.png)

No se si queríais arreglar esto en el sprint de estilar los componentes, pero si quereis tener ya popups funcionales os recomiendo `react-popupbox`.

**Comment by jmarindiez** [comment]
No nos habíamos dado cuenta de eso. Al hacerlo todo de manera independiente es difícil.

Si tienes alguna propuesta de como ponerlo en App así para ir desarrollando los componentes dínoslo. Por que lo hacemos borrando todo el app y renderizando solo el componente concreto.

Lo de popup-box lo miraré. No sabia muy bien hasta que punto meter dependencias.

**Comment by xzebra** [comment]
> No nos habíamos dado cuenta de eso. Al hacerlo todo de manera independiente es difícil.
> 
> Si tienes alguna propuesta de como ponerlo en App así para ir desarrollando los componentes dínoslo. Por que lo hacemos borrando todo el app y renderizando solo el componente concreto.

Yo recomiendo que los componentes que no se van a mostrar a pantalla completa (popups, el chat si es un desplegable, etc), los pongais con una pantalla completa "de fondo" para ver como interaccionan entre ellos.

> Lo de popup-box lo miraré. No sabia muy bien hasta que punto meter dependencias.

Dependencias las que queráis, mirad siempre porque la mayoría de las cosas que se quieren hacer ya están hechas. No reinventéis la rueda a no ser que sea necesaria una rueda cuadrada.
