### ISSUE TITLE
Equis para cerrar el pop-up

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/web#67]
Estaria bien que hubiera una X para cerrar el popup como esto, porque como te venga una abuela no sabra cerrarlo:

![image](https://user-images.githubusercontent.com/25647296/113198477-42cd4380-9266-11eb-8b20-498cac1c7249.png)

**Comment by jmarindiez** [comment]
En principio miramos que todos tuviesen botones para que se pudiese salir de ahí  con Cancelar, Atras etc. Pero si, se podría añadir también.

Pero ojo, no a todos, porque hay algunos que interesa que no se puedan cerrar.

**Comment by marioortizmanero** [comment]
Bueno en verdad si tienen todos un boton de cancelar no es del todo necesario, pero el seguir un esquema consistente con la X hace que sea mas facil de encontrar porque no hace falta ni leer el boton. No cai en eso, puedes cerrar el issue si no te parece lo suficientemente importante.
