### ISSUE TITLE
Detalles pendientes

### ISSUE THREAD

**Issue by FCanfran** [UNIZAR-30226-2021-07/web#70]
Ponerse de acuerdo con los de móvil en todos los colores/bordes/sombreado de los botones

**Comment by FCanfran** [comment]
- [ ] Color de hover de los botones
- [ ] Navegación de imágenes -> poner links a imágenes

**Comment by jmarindiez** [comment]
- [x] Utilizar contextos para datos compartidos (token, username)
[Enlace a info sobre contextos](https://stackoverflow.com/questions/53346462/react-multiple-contexts/53346541)
