### ISSUE TITLE
Errores javascript

### ISSUE THREAD

**Issue by FCanfran** [UNIZAR-30226-2021-07/web#83]
- [ ] Los errores de javascript le saldrán al cliente normal, o solo a nosotros por estar desarrollando? -> Es por poner un tratamiento mejor de algunos errores, como ante caída del server

**Comment by xzebra** [comment]
Le saldrán a cualquier persona que tenga la consola abierta (no es muy dficil abrirla), así que mientras no haya información sensible, no importan. Normalmente se intentan evitar y se muestran a los usuarios de otra forma (para eso tenemos el popup).
