### ISSUE TITLE
No se esta desplegando bien la web

### ISSUE THREAD

**Issue by jmarindiez** [UNIZAR-30226-2021-07/web#85]
La web no se esta desplegando bien [aqui](https://unizar-30226-2021-07.github.io/web).

El contenido sale aún sin centrar y la funcionalidad hecha no aparece todavía. Es como que lleva un tiempo sin desplegarse.

![imagen](https://user-images.githubusercontent.com/45235914/113586157-74128e80-962d-11eb-83c2-2f3aab4f54c9.png)

@marioortizmanero @xzebra

**Comment by xzebra** [comment]
Es verdad que no está centrada, pero el codigo es el que es. De hecho la funcionalidad hecha sí que está porque está todo lo del token, lo único que fallan las CORS.

**Comment by xzebra** [comment]
Se debe a que está cogiendo el margin:0 de .app_component antes que los margin:auto de container. Lo que no sé es por qué en local lo coge en un orden y en el despliegue otro

**Comment by xzebra** [comment]
https://stackoverflow.com/a/61157369

Una solución aparente al reordenado es crear un solo fichero css usando scss: https://stackoverflow.com/a/54309363
